# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.mdadmConf = ''
    array /dev/md1 
  '';

  boot.supportedFilesystems = [ "ntfs" ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/08b40c5b-f741-4dbd-8383-6f63acc23922";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/261D-0385";
    fsType = "vfat";
  };

  fileSystems."/run/mount/c" = {
    device = "/dev/disk/by-uuid/D854297E5429610C";
    fsType = "ntfs";
    options = [ "rw" "uid=${builtins.toString config.users.users.becca.uid}" ];
  };

  fileSystems."/run/mount/d" = {
    device = "/dev/disk/by-partuuid/25324fe6-c414-11e2-bb89-c85593649ce7";
    fsType = "ntfs";
    options = [ "rw" "uid=${builtins.toString config.users.users.becca.uid}" ];
  };

  fileSystems."/run/mount/e" = {
    device = "/dev/disk/by-uuid/4ED6AD0AD6ACF37F";
    fsType = "ntfs";
    options = [ "rw" "uid=${builtins.toString config.users.users.becca.uid}" ];
  };

  # RAID 1 volume; /dev/sdb and /dev/sdc
  fileSystems."/run/mount/mirrored" = {
    device = "/dev/disk/by-uuid/7CC46C67C46C259C";
    fsType = "ntfs";
    options = [ "rw" "uid=${builtins.toString config.users.users.becca.uid}" ];
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
